// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

Future<List<TodoItem>> loadTodos({required String path}) =>
    RustLib.instance.api.crateApiSimpleLoadTodos(path: path);

Future<void> saveTodos({required String path, required List<TodoItem> items}) =>
    RustLib.instance.api.crateApiSimpleSaveTodos(path: path, items: items);

Future<List<TodoItem>> addTodo({
  required String path,
  required List<TodoItem> items,
  required String title,
}) => RustLib.instance.api.crateApiSimpleAddTodo(
  path: path,
  items: items,
  title: title,
);

Future<List<TodoItem>> removeTodo({
  required String path,
  required List<TodoItem> items,
  required BigInt index,
}) => RustLib.instance.api.crateApiSimpleRemoveTodo(
  path: path,
  items: items,
  index: index,
);

class TodoItem {
  final String title;
  final bool isDone;

  const TodoItem({required this.title, required this.isDone});

  @override
  int get hashCode => title.hashCode ^ isDone.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoItem &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          isDone == other.isDone;
}
